language: python
sudo: false

env:
  - PSYCOPG2_TESTDB_USER=postgres

matrix:
  fast_finish: true
  include:
    - python: 2.6
    - python: 3.2
      if: branch = python3
    - python: pypy
    - python: pypy3
      if: branch = python3

script:
  - echo $PSYCOPG2_TESTDB_USER
  - python -V

