language: shell
sudo: false
os: linux

jobs:
  include:
    - script: echo hi
      if: env(TRAVIS_COMMIT_MESSAGE) =~ abcdef
    - script: echo hi2
      if: env(TRAVIS_COMMIT_MESSAGE) =~ tuvwxy
    - script: echo hi3
      if: NOT env(TRAVIS_COMMIT_MESSAGE) =~ tuvwxy


