language: shell
sudo: false

matrix:
  fast_finish: true
  include:
    - env: SOMETHING=4
      if: branch = master
    - env: SOMETHING=5
    - env: SOMETHING=6
      if: branch = secondary

script:
  - ./run.sh

