language: shell

matrix:
 fast_finish: true
 include:
  - env: FOO=1
    os: osx
    osx_image: xcode9.3
    if: branch = master
  - env: FOO=2
    os: osx
    osx_image: xcode9.3-moar
    if: branch = master


script:
  - echo $FOO
