language: shell
sudo: false

matrix:
  include:
    - env: IMAGE=0
      os: linux
    - env: IMAGE=1
      os: linux
    - env: IMAGE=2
      os: osx
    - env: IMAGE=3
      os: osx
    - env: IMAGE=4
      os: linux
    - env: IMAGE=5
      os: linux
    - env: IMAGE=6
      os: linux
    - env: IMAGE=7
      os: linux
    - env: IMAGE=8
      os: linux
    - env: IMAGE=9
      os: osx
    - env: IMAGE=10
      os: osx
    - env: IMAGE=11
      os: osx
    - env: IMAGE=12
      os: linux
    - env: IMAGE=13
      os: linux
    - env: IMAGE=14
      os: linux
    - env: IMAGE=15
      os: linux
    - env: IMAGE=16
      os: linux

script:
  - date
  - sleep 30
  - date
