language: shell
sudo: false

matrix:
  fast_finish: true
  include:
    - env: SOMETHING=4
    - env: SOMETHING=6
      if: type = pull_request

env:
  global:
    - MORETHING=8

before_install:
  - echo before_install

install:
  - echo install

before_script:
  - echo before_script

script:
  - ./run.sh

after_success:
  - echo after_success

after_failure:
  - echo after_failure

before_cache:
  - echo before_cache

before_deploy:
  - echo before_deploy

